version: '3'

vars:
  ORG: danskernesdigitalebibliotek
  MIGRATION_FILE: .migration-info

includes:
  migration: ./migration/Taskfile.migration.yml

tasks:
  # --------------------------------------------------------------------------
  # Public Tasks (Entry Points)
  # --------------------------------------------------------------------------
  dev:design:bundle:
    desc: "Bundle local design changes, and make accessible for CMS and React."
    silent: true
    cmds:
      - (cd design-system && task dev:build)
      - (cd design-system && ./bundle.sh)
      - mv design-system/dist.zip cms/packages/dpl-design-system.zip
      # TODO: Use task dev:cli -- instead of dce.
      # We need to remove the package, as composer will avoid installing it
      # otherwise as it sees no version change.
      - (cd cms && dce composer remove "danskernesdigitalebibliotek/dpl-design-system")
      - (cd cms && dce composer clear-cache)
      - (cd cms && dce composer require "danskernesdigitalebibliotek/dpl-design-system:dev-local")
      - (cd cms && dce drush cr)
      - (cd react && yarn install && yarn build)

  dev:react:bundle:
    desc: "Bundle local react changes, and make accessible for CMS."
    silent: true
    cmds:
      # TODO: Use task dev:cli -- instead of dce.
      - (cd react && yarn build)
      - rm -f cms/packages/dpl-react.zip
      # Same type of zip as happens in react-create-release-on-tag.yml workflow.
      - zip -r -j cms/packages/dpl-react.zip react/dist
      # TODO: Use task dev:cli -- instead of dce.
      # We need to remove the package, as composer will avoid installing it
      # otherwise as it sees no version change.
      - (cd cms && dce composer remove "danskernesdigitalebibliotek/dpl-react")
      - (cd cms && dce composer clear-cache)
      - (cd cms && dce composer require "danskernesdigitalebibliotek/dpl-react:dev-local")
      - (cd cms && dce drush cr)
