---
name: CMS / Webmaster config check
on:
  pull_request:
    paths:
      - 'cms/config/sync/core.extension.yml'
      - 'cms/config/sync/user.role.*.yml'
jobs:
  checkRoles:
    name: Check roles has been updated correctly
    uses: ./.github/workflows/cms-webmaster-config-workflow.yml
    with:
      trigger-path: 'cms/config/sync/user.role.*.yml'
      target-code: '_dpl_update_alter_permissions'

  checkModules:
    name: Check roles has been updated correctly
    uses: ./.github/workflows/cms-webmaster-config-workflow.yml
    with:
      trigger-path: 'cms/config/sync/core.extension.yml'
      target-code: '_dpl_update_install_modules'
