name: Design / Lint

on:
  pull_request:
    paths:
      - 'design-system/**'
      - '.github/workflows/design-system-*.yml'
  push:
    branches:
      - main
    paths:
      - 'design-system/**'
      - '.github/workflows/design-system-*.yml'

jobs:
  css-lint:
    name: CSS Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: design-system
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Run css:lint
        run: yarn css:lint

  js-lint:
    name: JS Linter
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: design-system
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Run js:lint
        run: yarn js:lint

  markdown-linkt:
    name: Markdown Linter
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: design-system
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Run markdown:lint
        run: yarn markdown:lint
