name: Design / Accessibility

on:
  pull_request:
    paths:
      - 'design-system/**'
      - '.github/workflows/design-system-*.yml'
  push:
    branches:
      - main
    paths:
      - 'design-system/**'
      - '.github/workflows/design-system-*.yml'

jobs:
  a11y:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: design-system
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v5
        with:
          node-version-file: 'design-system/.nvmrc'
      - run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Compile styles
        run: yarn css:build

      - name: Run accessibility tests
        run: yarn storybook:axe
