# Workflow name
name: Go / Chromatic

# Event for the workflow
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'

# List of jobs
jobs:
  chromatic-deployment:
    name: Go / Chromatic

    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Make sure the actual branch is checked out when running on pull requests.
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: actions/setup-node@v5
        with:
          node-version-file: "go/.nvmrc"

      - name: Load environment variables
        uses: cardinalby/export-env-action@v2
        with:
          envFile: "go/.env.test"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish to Chromatic
        uses: chromaui/action@v13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_GO }}
          workingDir: go
