name: "Go / Prettier check"

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Make sure the actual branch is checked out when running on pull requests.
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: actions/setup-node@v5
        with:
          node-version-file: "go/.nvmrc"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check Prettier formatting
        run: yarn run format:check
