# Workflow name
name: "Go / Unit test"

# Event for the workflow
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'go/**'
      - '.github/workflows/go-*.yml'

# List of jobs
jobs:
  unit:
    name: Unit test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          # Make sure the actual branch is checked out when running on pull requests.
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: actions/setup-node@v5
        with:
          node-version-file: "go/.nvmrc"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test:unit:once
