name: React / RelativeCI

on:
  push:
    paths:
      - 'react/**'
      - '.github/workflows/react-*.yml'
  pull_request:
    paths:
      - 'react/**'
      - '.github/workflows/react-*.yml'

jobs:
  build-and-send:
    name: React / Build artifacts
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react
    steps:
      - uses: actions/checkout@v6
        with:
          # Required to fetch all commits and tags
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version-file: 'react/.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'react/yarn.lock'
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build artifacts
        run: |
          yarn install
          yarn build:css:prod
          VERSION_FILE_NAME=$GITHUB_REPOSITORY \
          VERSION_FILE_VERSION=$(git describe --tags --exclude=latest) \
          yarn build:js:prod --json webpack-stats.json

      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v3
        with:
          key: ${{ secrets.RELATIVE_CI_KEY_REACT }}
          token: ${{ secrets.GITHUB_TOKEN }}
          webpackStatsFile: ./react/webpack-stats.json
