---
name: React / Tag-release (workflow)

on:
  workflow_call:

jobs:
  create_release:
    name: React / Create release on branch changes
    uses: ./.github/workflows/common-release-workflow.yml
    with:
      project: 'react'
      sha: ${{ github.sha }}
      branch: ${{ github.ref_name }}
      dev_release: false
